---
name: Nix Cache
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [pi@raspberrypi, jga@yoga, jsg@amd]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v12
        with:
          name: jgalabs-homelab
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Build home-manager configuration ${{ matrix.config }}
        run: nix build .#homeConfigurations."${{ matrix.config }}".activationPackage
